server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/novelWeb?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456 # tuỳ mk moi may
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
api:
  prefix: /api/v1